### ISSUE TITLE
Running pip on python-3.3 cartage fails on hosted OpenShift.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin-server#6031] opened 2014-12-29 22:58 UTC
The python-3.3 cartridge on hosted OpenShift is using a recent version of ``pip``. This version of ``pip`` though requires that the user home directory is writable. Under hosted OpenShift this isn't the case though and so use of ``requirements.txt`` file of direct use of ``pip`` fails.

```
$ rhc app-create pipfailtest python-3.3 --no-git
Application Options
-------------------
Domain:     grahamdumpleton
Cartridges: python-3.3
Gear Size:  default
Scaling:    no

Creating application 'pipfailtest' … done

Waiting for your DNS name to be available ... done

Your application 'pipfailtest' is now available.

  URL:        http://pipfailtest-grahamdumpleton.rhcloud.com/
  SSH to:     xxx@pipfailtest-grahamdumpleton.rhcloud.com
  Git remote: ssh://xxx@pipfailtest-grahamdumpleton.rhcloud.com/~/git/pipfailtest.git/

Run 'rhc show-app pipfailtest' for more details about your app.

$ ssh xxx@pipfailtest-grahamdumpleton.rhcloud.com

[pipfailtest-grahamdumpleton.rhcloud.com xxx]\> pip install antigravity
Collecting antigravity
Traceback (most recent call last):
  File "/opt/rh/python33/root/usr/lib64/python3.3/logging/handlers.py", line 72, in emit
    if self.shouldRollover(record):
  File "/opt/rh/python33/root/usr/lib64/python3.3/logging/handlers.py", line 185, in shouldRollover
    self.stream = self._open()
  File "/var/lib/openshift/xxx/python/virtenv/venv/lib/python3.3/site-packages/pip/utils/logging.py", line 119, in _open
    os.makedirs(os.path.dirname(self.baseFilename))
  File "/opt/rh/python33/root/usr/lib64/python3.3/os.py", line 258, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/rh/python33/root/usr/lib64/python3.3/os.py", line 258, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/rh/python33/root/usr/lib64/python3.3/os.py", line 269, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/lib/openshift/xxx/.cache'
```

It is arguable as to whether ``pip`` is really doing the right thing here in fail and not falling back to something else, but the workaround is to set two additional XDG environment variables on top of the ``XDG_DATA_DIRS`` environment variable which is already being set. So either:

```
   XDG_CACHE_HOME=$OPENSHIFT_REPO_DIR/.cache
   XDG_CONFIG_DIRS=$OPENSHIFT_REPO_DIR/.config
```

or maybe:

```
   XDG_CACHE_HOME=$OPENSHIFT_PYTHON_DIR/run/.cache
   XDG_CONFIG_DIRS=$OPENSHIFT_PYTHON_DIR/run/.config
```

This would need to be set up in the ``update-configuration`` script.

* https://github.com/openshift/origin-server/search?utf8=✓&q=XDG

I would image that in time this problem will also hit Python 2.7 cartridge if it is every updated so as to use a new ``pip`` version. So not just the Python 3.3 cartridge needs to be changed.

To test that those environment variables avoid the problem, you can use:

```
rhc set-env -a pipfailtest XDG_CACHE_HOME=/tmp/.cache XDG_CONFIG_DIRS=/tmp/.config
```

and restart the gear, ssh in again and try running ``pip`` again.

**Comment by tiwillia** [comment] 2015-07-08 20:59
This issue is documented in [Bugzilla #1225291](https://bugzilla.redhat.com/show_bug.cgi?id=1225291) and was resolved with commit b07ec8b3342ec83276a54d62551b6dc0cf1588ba

I was unable to reproduce the issue in OpenShift online.

@danmcp this can be closed.

**Closed** 2015-07-08 22:29 UTC
